const f = () => {


    try {
        let a = 0;
       // console.log(program);
        console.log("program run successfully");
    } catch (err) {
        console.log("this is an error");
        console.log(p);
    } finally {
        console.log("i am a good boy");
        //close the file
        //exit the loop
        //write to the log file;
    }

}

f()